# Generated by Django 2.2.1 on 2019-11-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('cost', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Luggage Type',
            },
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(blank=True)),
                ('space_alloted', models.IntegerField()),
                ('space_status', models.BooleanField(default=False)),
                ('type', models.ManyToManyField(to='luggage.LuggageType')),
            ],
            options={
                'verbose_name_plural': 'Luggage',
            },
        ),
    ]
