# Generated by Django 2.2.1 on 2019-11-08 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('cost', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Luggage Type',
            },
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_alloted', models.IntegerField()),
                ('space_status', models.BooleanField(default=False)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggageaccomodator', to=settings.AUTH_USER_MODEL)),
                ('type', models.ManyToManyField(related_name='types', to='luggage.LuggageType')),
            ],
            options={
                'verbose_name_plural': 'Luggage',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggagekeeper', to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage', to='luggage.Luggage')),
            ],
            options={
                'verbose_name_plural': 'Booking',
            },
        ),
    ]
