# Generated by Django 2.2.1 on 2019-11-08 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luggageaccomodator', to=settings.AUTH_USER_MODEL),
        ),
    ]
