# Generated by Django 2.2.1 on 2019-11-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
