# Generated by Django 2.2.1 on 2019-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0002_auto_20191107_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='type',
            field=models.ManyToManyField(related_name='types', to='luggage.LuggageType'),
        ),
    ]
