# Generated by Django 2.2.1 on 2019-11-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0003_auto_20191107_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
