# Generated by Django 2.2.1 on 2019-11-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0004_auto_20191107_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggage',
            name='owner_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggage.Luggage')),
            ],
            options={
                'verbose_name_plural': 'Booking',
            },
        ),
    ]
