# Generated by Django 2.2.1 on 2019-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0005_auto_20191107_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
