# Generated by Django 2.2.1 on 2019-11-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0006_booking_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage', to='luggage.Luggage'),
        ),
    ]
