# Generated by Django 2.2.1 on 2019-11-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0008_auto_20191107_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner_name',
            new_name='owner_id',
        ),
    ]
